server:
  port: 5000
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: User-Service
          uri:
            lb://User-Service
          predicates:
            - Path=/auth/**,/users/**,/api/users/**,/
        - id: Student-Fee-Service
          uri:
            lb://Student-Fee-Service
          predicates:
            - Path=/api/bills/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"


eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/